import fs from 'node:fs/promises';
import vm from 'node:vm';
import {createHash,randomUUID,pbkdf2Sync} from 'node:crypto';
export async function harness(seed={sources:[],entries:[]},password='test-only-password'){
 const props={AUTH_SALT:'test-salt',AUTH_HASH:createHash('sha256').update(pbkdf2Sync(password,'test-salt',600000,32,'sha256').toString('hex')).digest('hex'),SPREADSHEET_ID:'test',BACKUP_FOLDER_ID:'test-backups'};
 seed.sources.forEach(s=>{if(s.deletedAt)props['trash:'+s.id]=String(s.deletedAt);});
 const cache=new Map(),triggers=[],backups=[];let now=Date.now(),writeFailure=null,backupFailure=false,triggerFailure=false,authorizationRequired=false;
 class Clock extends Date {static now(){return now;}}
 const storage={'Источники':[['ID','Название','Статус','Цвет','Порядок'],...seed.sources.map(s=>[s.id,s.name,s.active?'Активный':'Неактивный',s.color,s.order])],'Доходы':[['Месяц','ID источника','Сумма, ₽'],...seed.entries.map(e=>[e.month,e.sourceId,e.amount/100])]};
 const sheet=name=>({deleteRow:r=>{if(writeFailure===name){writeFailure=null;throw new Error('Simulated row deletion failure');}storage[name].splice(r-1,1);},getLastRow:()=>storage[name].length,getMaxRows:()=>100000,getRange:(r,c,h,w)=>({getValues:()=>Array.from({length:h},(_,i)=>Array.from({length:w},(_,j)=>storage[name][r-1+i]?.[c-1+j]??'')),setValues:rows=>{if(writeFailure===name){writeFailure=null;throw new Error('Simulated sheet write failure');}rows.forEach((row,i)=>{storage[name][r-1+i]??=[];row.forEach((value,j)=>storage[name][r-1+i][c-1+j]=structuredClone(value));});}})});
 const driveFile=(name,contents)=>{const record={id:randomUUID(),name,contents,createdAt:now,description:'',trashed:false};backups.push(record);return {getId:()=>record.id,getName:()=>record.name,getDateCreated:()=>new Clock(record.createdAt),setDescription:value=>{record.description=value;},setTrashed:value=>{record.trashed=value;}};};
 const folder={createFile:(name,contents)=>{if(backupFailure){backupFailure=false;throw new Error('Simulated backup failure');}return driveFile(name,contents);},getFiles:()=>{const values=backups.filter(file=>!file.trashed).map(file=>({getId:()=>file.id,getName:()=>file.name,getDateCreated:()=>new Clock(file.createdAt),setTrashed:value=>{file.trashed=value;}}));let index=0;return {hasNext:()=>index<values.length,next:()=>values[index++]};}};
 const context=vm.createContext({console,Date:Clock,PropertiesService:{getScriptProperties:()=>({getProperty:key=>props[key]??null,getProperties:()=>({...props}),setProperty:(key,value)=>{props[key]=value;},deleteProperty:key=>{delete props[key];}})},CacheService:{getScriptCache:()=>({get:key=>{const v=cache.get(key);return v&&v.expires>now?v.value:null;},put:(key,value,seconds)=>cache.set(key,{value,expires:now+seconds*1000}),remove:key=>cache.delete(key)})},LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock:()=>{}})},Utilities:{DigestAlgorithm:{SHA_256:'sha256'},Charset:{UTF_8:'utf8'},computeDigest:(_,value)=>[...createHash('sha256').update(value).digest()],getUuid:randomUUID,formatDate:d=>d.toISOString().slice(0,7)},ContentService:{MimeType:{JSON:'json'},createTextOutput:text=>({text,setMimeType(){return this;}})},MimeType:{PLAIN_TEXT:'text/plain'},DriveApp:{getFolderById:id=>{if(id!=='test-backups')throw new Error('Missing test folder');return folder;}},SpreadsheetApp:{openById:()=>({getSheetByName:sheet}),flush:()=>{}}});
 context.ScriptApp={AuthMode:{FULL:'FULL'},AuthorizationStatus:{REQUIRED:'REQUIRED'},getAuthorizationInfo:()=>({getAuthorizationStatus:()=>authorizationRequired?'REQUIRED':'NOT_REQUIRED',getAuthorizationUrl:()=> 'https://script.google.com/test-only-authorization'}),EventType:{CLOCK:'CLOCK'},getProjectTriggers:()=>triggers,newTrigger:handler=>{if(triggerFailure)throw new Error('Trigger authorization required');const t={getHandlerFunction:()=>handler,getEventType:()=> 'CLOCK'};const builder={timeBased:()=>builder,everyHours:hours=>{t.hours=hours;return builder;},everyDays:days=>{t.days=days;return builder;},atHour:hour=>{t.hour=hour;return builder;},create:()=>{triggers.push(t);return t;}};return builder;}};
 vm.runInContext(await fs.readFile(new URL('../server/Code.gs',import.meta.url),'utf8'),context);
 return {request:body=>JSON.parse(context.doPost({postData:{contents:JSON.stringify(body)}}).text),props,storage,cache,triggers,backups,runCleanup:()=>context.purgeExpiredSources(),runScheduledBackup:()=>context.createScheduledBackup(),failNextWrite:name=>{writeFailure=name;},failNextBackup:()=>{backupFailure=true;},failTrigger:()=>{triggerFailure=true;},requireAuthorization:()=>{authorizationRequired=true;},advance:ms=>{now+=ms;},now:()=>now,proof:pbkdf2Sync(password,props.AUTH_SALT,600000,32,'sha256').toString('hex')};
}
